ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

# 安装hanlp。会安装TF2
RUN pip install hanlp && \
	# 主体模型
	pip install --upgrade gensim && \
	# 北大中文
	pip install pkuseg && \
	# 清华中文
	pip install thulac